    # Archivo de Secrets para Streamlit Community Cloud
    # Este archivo contiene las credenciales de tu base de datos Supabase.
    # Streamlit lo leerá automáticamente cuando despliegues tu aplicación.

    # Credenciales de Supabase PostgreSQL (¡USANDO EL TRANSACTION POOLER!)
    DB_HOST = "aws-0-us-east-2.pooler.supabase.com" # <--- ¡HOST DE TU POOLER! (ej. aws-0-us-east-2.pooler.supabase.com)
    DB_NAME = "postgres"
    DB_USER = "postgres.zugpocccdmbfcnlqaxju" # <--- ¡USUARIO DE TU POOLER! (ej. postgres.tu_project_ref)
    DB_PASSWORD = "|A058{S04t" # Asegúrate de que esta sea tu contraseña real de Supabase
    DB_PORT = "6543" # <--- ¡PUERTO DE TU POOLER! (6543 para Transaction Pooler, 5432 para Session Pooler)
    
