# Archivo de Secrets para Streamlit Community Cloud
# Este archivo contiene las credenciales de tu base de datos Supabase.
# Streamlit lo leerá automáticamente cuando despliegues tu aplicación.

# Credenciales de Supabase PostgreSQL
DB_HOST = "aws-0-us-east-2.pooler.supabase.com"
DB_NAME = "postgres"
DB_USER = "postgres.zugpocccdmbfcnlqaxju"
DB_PASSWORD = "|A058.S04t." # Asegúrate de que esta sea tu contraseña real de Supabase
DB_PORT = "6543"
