    # Archivo de Secrets para Streamlit Community Cloud
    # Este archivo contiene las credenciales de tu base de datos Supabase.
    # Streamlit lo leerá automáticamente cuando despliegues tu aplicación.

    # Credenciales de Supabase PostgreSQL (¡USANDO EL POOLER!)
    DB_HOST = "aws-0-sa-east-1.pooler.supabase.com" # <--- ¡CAMBIA ESTO POR EL HOST DE TU POOLER!
    DB_NAME = "postgres"
    DB_USER = "postgres"
    DB_PASSWORD = "|A058{S04t" # Asegúrate de que esta sea tu contraseña real de Supabase
    DB_PORT = "6543" # <--- ¡CAMBIA ESTO POR EL PUERTO DE TU POOLER!
    